import Link from 'next/link'
import { createClient } from '@/utils/supabase/server'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { ArrowRight, Clock } from 'lucide-react'

export const metadata = {
    title: 'Explore Video Guides - StepSnip',
    description: 'Discover the latest step-by-step guides generated from YouTube videos. Browse our collection of community-created tutorials.',
}

export default async function ExplorePage() {
    const supabase = await createClient()

    // Fetch latest 50 completed projects
    const { data: projects } = await supabase
        .from('projects')
        .select('id, title, created_at, video_source_url')
        .eq('status', 'completed')
        .order('created_at', { ascending: false })
        .limit(50)

    return (
        <div className="container py-12 px-4 md:px-6">
            <div className="mb-10 text-center max-w-2xl mx-auto">
                <h1 className="text-3xl font-bold mb-4">Explore Recent Guides</h1>
                <p className="text-muted-foreground text-lg">
                    Discover the latest step-by-step tutorials generated by the community.
                    Turn any YouTube video into a clear, visual guide.
                </p>
            </div>

            {(!projects || projects.length === 0) ? (
                <div className="text-center py-20">
                    <p className="text-muted-foreground">No guides found yet. Be the first to create one!</p>
                    <Button asChild className="mt-4">
                        <Link href="/">Create Guide</Link>
                    </Button>
                </div>
            ) : (
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                    {projects.map((project) => (
                        <Link key={project.id} href={`/guides/${project.id}`} className="block group h-full">
                            <Card className="h-full hover:shadow-lg transition-all duration-300 border-transparent hover:border-primary/20 bg-card/50 hover:bg-card">
                                <CardHeader>
                                    <CardTitle className="text-lg line-clamp-2 leading-tight group-hover:text-primary transition-colors">
                                        {project.title || 'Untitled Video Guide'}
                                    </CardTitle>
                                </CardHeader>
                                <CardContent>
                                    <div className="space-y-4">
                                        <div className="bg-muted/30 rounded-md p-3 text-xs text-muted-foreground break-all line-clamp-1">
                                            {project.video_source_url}
                                        </div>

                                        <div className="flex items-center justify-between text-sm text-muted-foreground pt-2 border-t">
                                            <div className="flex items-center gap-1">
                                                <Clock className="w-3 h-3" />
                                                <span>{new Date(project.created_at).toLocaleDateString()}</span>
                                            </div>
                                            <span className="group-hover:translate-x-1 transition-transform inline-flex items-center gap-1 text-primary text-xs font-medium">
                                                View Guide <ArrowRight className="w-3 h-3" />
                                            </span>
                                        </div>
                                    </div>
                                </CardContent>
                            </Card>
                        </Link>
                    ))}
                </div>
            )}

            <div className="mt-16 text-center">
                <Button asChild size="lg" variant="outline">
                    <Link href="/">Create Your Own Guide</Link>
                </Button>
            </div>
        </div>
    )
}
