import Link from 'next/link'
import Image from 'next/image'
import { createClient } from '@/utils/supabase/server'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { ArrowRight, Clock, PlayCircle } from 'lucide-react'

// Helper function to extract YouTube video ID from URL
function extractYouTubeId(url: string): string | null {
    const regExp = /^.*(youtu.be\/|v\/|u\/\w\/|embed\/|watch\?v=|&v=)([^#&?]*).*/;
    const match = url?.match(regExp);
    return (match && match[2].length === 11) ? match[2] : null;
}

export const metadata = {
    title: 'Explore Popular How-to Guides & Video Tutorials - StepSnip',
    description: 'Browse thousands of step-by-step guides generated from YouTube videos. Find tutorials on coding, design, cooking, tech support and more.',
    keywords: ['how to guides', 'video tutorials', 'step by step instructions', 'youtube tutorials', 'visual guides'],
}

export default async function ExplorePage() {
    const supabase = await createClient()

    // Fetch latest 50 completed projects
    const { data: projects } = await supabase
        .from('projects')
        .select('id, title, created_at, video_source_url')
        .eq('status', 'completed')
        .order('created_at', { ascending: false })
        .limit(50)

    return (
        <div className="container py-12 px-4 md:px-6">
            <div className="mb-10 text-center max-w-2xl mx-auto">
                <h1 className="text-3xl font-bold mb-4">Explore Recent Guides</h1>
                <p className="text-muted-foreground text-lg">
                    Discover the latest step-by-step tutorials generated by the community.
                    Turn any YouTube video into a clear, visual guide.
                </p>
            </div>

            {(!projects || projects.length === 0) ? (
                <div className="text-center py-20">
                    <p className="text-muted-foreground">No guides found yet. Be the first to create one!</p>
                    <Button asChild className="mt-4">
                        <Link href="/">Create Guide</Link>
                    </Button>
                </div>
            ) : (
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                    {projects.map((project) => {
                        const videoId = extractYouTubeId(project.video_source_url);
                        const thumbnailUrl = videoId
                            ? `https://img.youtube.com/vi/${videoId}/hqdefault.jpg`
                            : null;

                        return (
                            <Link key={project.id} href={`/guides/${project.id}`} className="block group h-full">
                                <Card className="h-full hover:shadow-xl transition-all duration-300 border-transparent hover:border-primary/20 overflow-hidden">
                                    {/* Thumbnail */}
                                    <div className="relative aspect-video w-full bg-muted overflow-hidden">
                                        {thumbnailUrl ? (
                                            <Image
                                                src={thumbnailUrl}
                                                alt={project.title || 'Video Guide'}
                                                fill
                                                className="object-cover group-hover:scale-105 transition-transform duration-500"
                                                unoptimized
                                            />
                                        ) : (
                                            <div className="w-full h-full flex items-center justify-center bg-gradient-to-br from-primary/10 to-primary/5">
                                                <PlayCircle className="w-16 h-16 text-primary/30" />
                                            </div>
                                        )}
                                        <div className="absolute inset-0 bg-black/0 group-hover:bg-black/10 transition-colors duration-300" />
                                    </div>

                                    <CardHeader>
                                        <CardTitle className="text-lg line-clamp-2 leading-tight group-hover:text-primary transition-colors">
                                            {project.title || 'Untitled Video Guide'}
                                        </CardTitle>
                                    </CardHeader>
                                    <CardContent>
                                        <div className="flex items-center justify-between text-sm text-muted-foreground pt-2 border-t">
                                            <div className="flex items-center gap-1">
                                                <Clock className="w-3 h-3" />
                                                <span>{new Date(project.created_at).toLocaleDateString()}</span>
                                            </div>
                                            <span className="group-hover:translate-x-1 transition-transform inline-flex items-center gap-1 text-primary text-xs font-medium">
                                                View Guide <ArrowRight className="w-3 h-3" />
                                            </span>
                                        </div>
                                    </CardContent>
                                </Card>
                            </Link>
                        );
                    })}
                </div>
            )}

            <div className="mt-16 text-center">
                <Button asChild size="lg" variant="outline">
                    <Link href="/">Create Your Own Guide</Link>
                </Button>
            </div>
        </div>
    )
}
