-- ==========================================
-- 步骤 0: 创建 IP 使用记录表 (修复 missing relation 错误)
-- ==========================================
CREATE TABLE IF NOT EXISTS public.ip_usage_logs (
    id bigint generated by default as identity primary key,
    client_ip text not null,
    usage_date date not null DEFAULT CURRENT_DATE,
    generation_count integer default 0,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    last_generation_at timestamp with time zone default timezone('utc'::text, now()),
    updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- 添加索引以加快查询速度
CREATE INDEX IF NOT EXISTS idx_ip_usage_logs_ip_date ON public.ip_usage_logs(client_ip, usage_date);

-- 启用 RLS (虽然此表主要由服务端函数读写，但开启是好习惯)
ALTER TABLE public.ip_usage_logs ENABLE ROW LEVEL SECURITY;

-- ==========================================
-- 步骤 1: 将新用户初始积分调整为 30
-- ==========================================
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  -- 创建 Customer 记录
  INSERT INTO public.customers (
    user_id,
    email,
    credits,          -- 🟢 修改点：默认 30 积分
    creem_customer_id,
    created_at,
    updated_at,
    metadata
  ) VALUES (
    NEW.id,
    NEW.email,
    30,               -- 🟢 修改点：默认 30 积分
    'auto_' || NEW.id::text,
    NOW(),
    NOW(),
    jsonb_build_object(
      'source', 'auto_registration', 
      'initial_credits', 30,
      'provider', NEW.raw_user_meta_data->>'provider' -- 记录是 Google 还是 Email 注册
    )
  );

  -- 记录积分历史（让用户知道这是注册送的）
  INSERT INTO public.credits_history (
    customer_id, 
    amount, 
    type, 
    description, 
    created_at
  ) VALUES (
    (SELECT id FROM public.customers WHERE user_id = NEW.id),
    30, 
    'add', 
    '🎉 新用户注册福利 (3次免费生成)', 
    NOW()
  );

  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ==========================================
-- 步骤 2: 升级 IP 速率限制 (防羊毛党核心)
-- ==========================================
-- 逻辑：允许每个 IP 每天消耗 "相当于 2 个新用户" 的额度 (例如 6 次生成)
-- 正常用户家里最多也就 2-3 个人注册，不会触发限制。
-- 羊毛党脚本一个 IP 注册 100 个号，第 3 个号开始就会被卡死。

CREATE OR REPLACE FUNCTION public.check_ip_rate_limit(client_ip text)
RETURNS boolean AS $$
DECLARE
    limit_record public.ip_usage_logs%rowtype;
    -- 🟢 限制阈值：每天允许 6 次生成请求 (30积分=3次，这里给 2 个人的宽限)
    max_generations constant integer := 6; 
BEGIN
    -- 查询该 IP 今天的记录
    SELECT * INTO limit_record 
    FROM public.ip_usage_logs 
    WHERE client_ip = check_ip_rate_limit.client_ip 
    AND usage_date = CURRENT_DATE;
    
    IF NOT FOUND THEN
        -- 如果今天没记录，插入一条，计数为 1，允许通过
        INSERT INTO public.ip_usage_logs (client_ip, usage_date, generation_count, last_generation_at)
        VALUES (check_ip_rate_limit.client_ip, CURRENT_DATE, 1, NOW());
        RETURN true;
    ELSE
        -- 如果有记录，检查次数
        IF limit_record.generation_count < max_generations THEN
            -- 未超限，计数+1，允许通过
            UPDATE public.ip_usage_logs 
            SET generation_count = generation_count + 1, 
                last_generation_at = NOW(),
                updated_at = NOW()
            WHERE id = limit_record.id;
            RETURN true;
        ELSE
            -- 🔴 超限，拒绝通过
            RETURN false;
        END IF;
    END IF;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
