import Link from "next/link";
import { Card, CardContent } from "@/components/ui/card";
import { ArrowRight, PlayCircle } from "lucide-react";

// Real examples generated by the engine
const EXAMPLES = [
    {
        id: "de20af43-61bf-4007-99d8-bff3757cd8b7",
        title: "Build a Next.js App",
        category: "Coding",
        image: "/images/examples/coding.jpg",
        steps: 14
    },
    {
        id: "79555d80-7f5f-417e-8d82-fb325597b911",
        title: "Mastering Photoshop Layers",
        category: "Design",
        image: "/images/examples/design.jpg",
        steps: 10
    },
    {
        id: "414083b5-1e99-460b-bc88-0e27a166f447",
        title: "Fix WiFi Connection Issues",
        category: "Tech Support",
        image: "/images/examples/wifi.jpg",
        steps: 6
    }
];

export function ExampleShowcase() {
    return (
        <section className="py-24 bg-muted/30">
            <div className="container px-4">
                <div className="text-center mb-16">
                    <h2 className="text-3xl font-bold mb-4">See What StepSnip Can Do</h2>
                    <p className="text-muted-foreground max-w-2xl mx-auto">
                        We transform messy video tutorials into clean, readable guides.
                        Check out these examples generated by our engine.
                    </p>
                </div>

                <div className="grid md:grid-cols-3 gap-8">
                    {EXAMPLES.map((example, i) => (
                        <Link key={i} href={`/guides/${example.id}`} className="group">
                            <Card className="overflow-hidden hover:shadow-xl transition-all duration-300 border-2 border-transparent hover:border-primary/10">
                                <div className="aspect-video bg-muted relative flex items-center justify-center group-hover:scale-105 transition-transform duration-500">
                                    {example.image && (
                                        <img
                                            src={example.image}
                                            alt={example.title}
                                            className="absolute inset-0 w-full h-full object-cover"
                                        />
                                    )}
                                    <PlayCircle className="w-12 h-12 text-white/80 z-10 relative drop-shadow-md" />

                                    <div className="absolute inset-0 bg-black/40 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center z-20">
                                        <span className="text-white font-medium flex items-center gap-2">
                                            View Guide <ArrowRight className="w-4 h-4" />
                                        </span>
                                    </div>
                                </div>
                                <CardContent className="p-6">
                                    <div className="text-xs font-semibold text-primary mb-2 uppercase tracking-wider">
                                        {example.category}
                                    </div>
                                    <h3 className="font-bold text-lg mb-2 group-hover:text-primary transition-colors">
                                        {example.title}
                                    </h3>
                                    <p className="text-sm text-muted-foreground">
                                        {example.steps} steps • AI Generated
                                    </p>
                                </CardContent>
                            </Card>
                        </Link>
                    ))}
                </div>
            </div>
        </section>
    );
}
